.dockerfile-section-container {
    align-items: center;
}

.dockerfile-output-textbox {
    margin-bottom: 20px;
}

.dockerfile-title-container {
    width: 350px;
}

.utility-img {
    width: 20px;
    height: 20px;
    margin-right: 15px;
}

.utility-img:hover {
    cursor: pointer;
}

.left {
    flex: 1;
    align-items: center;
}

.center {
    flex: 1;
    align-items: center;
    justify-content: center;
}

.right {
    flex: 1;
    align-items: center;
    justify-content: flex-end;
}
